version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tfm-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jiaarafq6psj"
s3_prefix = "tfm-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["RootService=019249439598.dkr.ecr.eu-west-1.amazonaws.com/tfm"]
parameter_overrides = "AppEnv=\"{{resolve:ssm:AppEnv:1}}\" AccessKey=\"{{resolve:ssm:accessKey:1}}\" SecretKey=\"{{resolve:ssm:secretKey:1}}\" AWSRegion=\"{{resolve:ssm:region:1}}\" LogglyKey=\"{{resolve:ssm:LogglyKey:1}}\" LogglySubdomain=\"{{resolve:ssm:LogglySubdomain:1}}\" S3Bucket=\"{{resolve:ssm:S3Bucket:1}}\" KafkaBroker=\"{{resolve:ssm:KafkaBroker:2}}\" KafkaClient=\"{{resolve:ssm:KafkaClient:1}}\" SentryDNS=\"{{resolve:ssm:SentryDNS:1}}\""
