AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Pollution Images Calculator -
  TFM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  AccessKey:
    Description: "Required. Access Key"
    Type: "String"
    Default: "{{resolve:ssm:accessKey:1}}"
  SecretKey:
    Description: "Required. Secret Key"
    Type: "String"
    Default: "{{resolve:ssm:secretKey:1}}"
  AWSRegion:
    Description: "Required. Region"
    Type: "String"
    Default: "{{resolve:ssm:region:1}}"
  LogglyKey:
    Description: "Required. Loggly"
    Type: "String"
    Default: "{{resolve:ssm:logglyKey:1}}"
  S3Bucket:
    Description: "Required. S3 Bucket"
    Type: "String"
    Default: "{{resolve:ssm:S3Bucket:1}}"

Resources:
  S3Images:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: images-tfm
#  KafkaCluster:
#    Type: 'AWS::MSK::Cluster'
#    Properties:
#      ClusterName: kafka-tfm
#      KafkaVersion: 2.2.1
#      NumberOfBrokerNodes: 1
#      BrokerNodeGroupInfo:
#        InstanceType: kafka.t3.small
#        ClientSubnets:
#          - subnet-41191127
#          - subnet-487e6500
  RootService:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tfm-root
      PackageType: Image
      ImageUri: 019249439598.dkr.ecr.eu-west-1.amazonaws.com/tfm
      Environment:
        Variables:
          AccessKey: !Ref AccessKey
          SecretKey: !Ref SecretKey
          AWSRegion: !Ref AWSRegion
          LogglyKey: !Ref LogglyKey
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Images
      Events:
        RootEndpoint:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
        TestEndpoint:
          Type: HttpApi
          Properties:
            Path: /test
            Method: any
#        CreateS3Images:
#          Type: S3
#          Properties:
#            Bucket: !Ref S3Images
#            Events: s3:ObjectCreated:*
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./img-scrapper
      Dockerfile: ./Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TFMApi:
    Description: "API Gateway endpoint URL for TFM functions"
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
  TFMFunction:
    Description: "TFM Express Lambda Function ARN"
    Value: !Sub TFMService.Arn
  TFMIamRole:
    Description: "Implicit IAM Role created for TFM"
    Value: !Sub TFMFunctionRole.Arn
